# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
         Blog\ModelBundle\Entity\Author:
                    algorithm: bcrypt


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    Elsa:  { password: admin, roles: [ 'ROLE_ADMIN' ] }
#                    Eddie: { password: admin, roles: [ 'ROLE_SUPER_ADMIN' ] }
#                    David: { password: admin, roles: [ 'ROLE_ADMIN' ] }
        our_db_provider:
                    entity:
                        class: ModelBundle:Author
                        property: name


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern: ^/admin/
            anonymous: ~
            form_login:
                provider: our_db_provider
                login_path: blog_admin_security_login
                check_path: blog_admin_security_logincheck
                target_path_parameter: blog_admin_post_index
            logout:
                path: blog_admin_security_logout
                target: /admin/post



    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin/post/((new|show)/?)?$', roles: ROLE_ADMIN }
        - { path: '^/admin/post/((?!(new|show)).)*/', roles: ROLE_SUPER_ADMIN }
        - { path: '^/admin/(tag|author)/', roles: ROLE_SUPER_ADMIN }

#
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
