<?php

namespace Blog\ModelBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsedTags()
    {
        $qb = $this->getQueryBuilder()
            ->leftJoin('posts_tags', 'ps')
            ->where('ps.post_id NOT NULL');

        return $qb->getQuery()->getResult();
    }


    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('ModelBundle:Tag')
            ->createQueryBuilder('t');

        return $qb;
    }

}
