parameters:
    author_manager.class: Blog\CoreBundle\Services\AuthorManager
    post_manager.class: Blog\CoreBundle\Services\PostManager

services:
    author.manager:
        class: %author_manager.class%
        arguments: ['@doctrine.orm.entity_manager']
    post.manager:
        class:  %post_manager.class%
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']



#    core.example:
#        class: Blog\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

